baseURL = "https://ottan.xyz/"
languageCode = "ja"
defaultContentLanguage = "ja"
publishDir = "public"
contentDir = "content"
title = "OTTAN.XYZ"
theme = "ottanxyz"
hasCJKLanguage = true
summaryLength = 150
canonifyURLs = true
disqusShortname = "ottanxyz"
paginate = 20
googleAnalytics = "UA-54519352-1"
rssLimit = 15
pygmentsCodeFences = true
pygmentsStyle = "github"

[blackfriday]
	hrefTargetBlank = true
	smartypants = false

[params]
	author = "ottan"
	favicon = "images/favicon.ico"
	twitter = "https://twitter.com/ottanxyz/"
	facebook = "https://www.facebook.com/ottanxyz/"
	github = "https://github.com/ottanxyz/"
	rss = "https://ottan.xyz/index.xml"

[social]
	twitter = "ottanxyz"
	twitter_domain = ""
	facebook = "ottanxyz"
	facebook_admin = "808819212572711"