baseURL = "https://ottan.xyz/"
languageCode = "ja"
defaultContentLanguage = "ja"
publishDir = "public"
contentDir = "content"
title = "OTTAN.XYZ"
theme = "ottanxyz"
hasCJKLanguage = true
summaryLength = 200
canonifyURLs = true
disqusShortname = "ottanxyz"
paginate = 20
googleAnalytics = "UA-54519352-1"

[params]
	author = "ottan"

[social]
	twitter = "ottanxyz"
	twitter_domain = ""
	facebook = "ottanxyz"
	facebook_admin = "808819212572711"