baseURL = "https://ottanxyz.netlify.com/"
LanguageCode = "ja"
title = "OTTAN.XYZ"
theme = "ottanxyz"
hasCJKLanguage = true

[menu]

  [[menu.main]]
    name = "Windows"
    url = "/categories/windows"
    weight = -110

  [[menu.main]]
    name = "Others"
    url = "/categories/others"
    weight = -110
