backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
  squash_merges: true
local_backend: true
media_folder: /static/images
public_folder: /images
publish_mode: editorial_workflow
collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/posts'
    create: true
    slug: '{{fields.slug}}'
    path: '{{year}}/{{month}}/{{slug}}'
    preview_path: '/posts/{{year}}/{{month}}/{{slug}}'
    media_folder: '../../../uploads/{{year}}/{{month}}'
    public_folder: '/uploads/{{year}}/{{month}}'
    identifier_field: title
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime', format: 'YYYY-MM-DD' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Tags', name: 'tags', widget: 'list' }
      - { label: 'Categories', name: 'categories', widget: 'list' }
      - { label: 'Slug', name: 'slug', widget: 'string' }
      - { label: 'Featured Image', name: 'featured_image', widget: 'image', required: false }
    sortableFields: ['title', 'date']