# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "OTTAN.XYZ"
license = "MIT"
# licenselink = "https://github.com/budparr/gohugo-theme-ananke/blob/master/LICENSE.md"
# description = "A Base theme for building full featured Hugo sites"
# homepage = "https://github.com/budparr/gohugo-theme-ananke"
tags = ["website","responsive", "Disqus", "blog"]
features = ["posts", "shortcodes", "comments"]
min_version = 0.52

[author]
  name = "ottan"
  homepage = "https://ottan.xyz"
