name: Publish post from issue

on:
  issues:
    types: ['labeled']

jobs:
  build:
    if: ${{ github.event.label.name == 'publish' }}
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Generate Post
        env:
          POST_TITLE: ${{ github.event.issue.title }}
          POST_BODY: ${{ github.event.issue.body }}
          POST_ID: ${{ github.event.issue.id }}
          POST_CATEGORY: ${{ github.event.issue.labels[0].name }}
        run: |
           YEAR=`date "+%Y"`
           MONTH=`date "+%m"`
           mkdir -p content/posts/$YEAR/$MONTH
           mkdir -p uploads/$YEAR/$MONTH
           
           cat > content/posts/$YEAR/$MONTH/$POST_ID.md << EOF
           ---
           draft: false
           title: $POST_TITLE
           date: ${{ github.event.issue.updated_at }}   
           type: post
           slug: $POST_ID
           category: ["${POST_CATEGORY}"]
           ---
           EOF
          
           echo "$POST_BODY" | while read line; do
             if [[ "$line" =~ \!\[.*\]\(https://(.*)\) ]]; then
               url="https://${BASH_REMATCH[1]}"
               wget -P uploads/$YEAR/$MONTH "$url"
               line=${line//$url/\/uploads\/$YEAR\/$MONTH\/$(basename "$url")}
             fi
             echo $line >> content/posts/$YEAR/$MONTH/$POST_ID.md
           done
            
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          delete-branch: true
          title: "publish: ${{ github.event.issue.title}}"
          assignees: ottanjp
          body: |
            Automagically sprouted for publishing.
            Merging will publish to: https://ottan.xyz/
              Closes #${{ github.event.issue.number }}
            reviewers: "${{ github.repository_owner }}"
            commit-message: "post: ${{ github.event.issue.title }}"
